baseURL = "https://docs.ultralist.io/"
languageCode = "en-us"
title = "Ultralist: Amazing task management for tech folks."
pygmentsUseClasses=true
theme = "docsy"

github_repo = "https://github.com/ultralist/ultralist-hugo-docs"

[params]
copyright = "Ultralist LLC"
privacy_policy = "/privacy"


[[menu.main]]
  name = "Github"
  url = "https://github.com/ultralist"
  weight = 1
[[menu.main]]
  name = "Docs"
  url = "/docs/cli/quickstart"
  weight = 2
[[menu.main]]
  name = "Pro Pricing"
  url = "/pricing"
  weight = 3
[[menu.main]]
  name = "Blog"
  url = "/blog"
  weight = 3

[params.links]
[[params.links.ultralist]]
	name = "Pro Pricing"
	url = "/pricing"
[[params.links.ultralist]]
	name = "Download"
	url = "https://github.com/ultralist/ultralist/releases"
[[params.links.ultralist]]
	name = "Docs"
	url = "/docs"
[[params.links.ultralist]]
	name = "Blog"
	url = "/blog"
[[params.links.docs]]
	name = "Quickstart"
	url = "/docs/cli/quickstart"
[[params.links.docs]]
	name = "Ultralist Pro"
	url = "/docs/pro"
[[params.links.docs]]
	name = "API docs"
	url = "/docs/pro/api"
[[params.links.more]]
	name = "Github"
	url = "https://github.com/ultralist"
